export const AREA_OF_INTEREST = [
  "TECHNICAL DEVELOPMENT",
  "OPEN SOURCE CONTRIBUTION",
  "MENTORSHIP",
  "EVENT MANAGEMENT",
  "PROGRAM MANAGEMENT",
  "MARKETING & GROWTH",
  "SOCIAL MEDIA",
  "PARTNERSHIPS & SPONSORSHIPS",
  "CONTENT CREATION",
  "COMMUNITY MANAGEMENT",
  "MODERATION",
  "VOLUNTEERING",
  "OTHER",
];

export default AREA_OF_INTEREST;
